classifieds/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from sevalinks.views import home, sevalinks_404, sevalinks_500

handler404 = 'sevalinks.views.sevalinks_404'
handler500 = 'sevalinks.views.sevalinks_500'
#handler403 = 'sevalinks.views.my_custom_permission_denied_view'
#handler400 = 'sevalinks.views.my_custom_bad_request_view'

urlpatterns = [
	url(r'^geo/', include('geolocate.urls')),
    url(r'^seva/', include('sevalinks.urls')),
    url(r'^contacts/', include('contacts.urls')),    
    url(r'^admin/', admin.site.urls),
    url(r'^404/', sevalinks_404, name='sevalinks_404'), 
    url(r'^500/', sevalinks_500, name='sevalinks_500'), 
    url(r'^$', home, name='home'),    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

friends/contrib/suggestions/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns("friends.contrib.suggestions.views",

    url(r"^suggested_friends/$",
        "suggested_friends",
        name="friends_suggestions_suggested_friends"),

    url(r"^import_contacts/$",
        "import_contacts",
        name="friends_suggestions_import_contacts"),

    url(r"^import_google_contacts/$",
        "import_google_contacts",
        name="friends_suggestions_import_google_contacts"),

    url(r"^import_facebook_contacts/$",
        "import_facebook_contacts",
        name="friends_suggestions_import_facebook_contacts"),

    url(r"^import_twitter_contacts/$",
        "import_twitter_contacts",
        name="friends_suggestions_import_twitter_contacts"),

    url(r"^import_yahoo_contacts/$",
        "import_yahoo_contacts",
        name="friends_suggestions_import_yahoo_contacts"),

    url(r"^import_linkedin_contacts/$",
        "import_linkedin_contacts",
        name="friends_suggestions_import_linkedin_contacts"),

    url(r"^oauth_access/", include("oauth_access.urls")),

)

friends/urls.py
from django.conf.urls import url
import views

urlpatterns = [

    url(r'^$',
       views.list_friends,
       name='friends_friends'),

    url(r'^invite/(?P<username>[\.\w]+)/$',
       views.invite_friend,
       name='friends_invite'),

    url(r'^remove/(?P<username>[\.\w]+)/$',
       views.remove_friend,
       name='friends_remove'),

    url(r'^block/(?P<username>[\.\w]+)/$',
       views.block_user,
       name='friends_block_user'),

    url(r'^unblock/(?P<username>[\.\w]+)/$',
       views.unblock_user,
       name='friends_unblock_user'),

    url(r'^blocked/$',
       views.list_blocked_users,
       name='friends_blocked_users'),

    url(r'^invitations/received/$',
       views.list_received_invitations,
       name='friends_received_invitations'),

    url(r'^invitations/sent/$',
       views.list_sent_invitations,
       name='friends_sent_invitations'),

    url(r'^invitation/(?P<invitation_id>[\d]+)/$',
       views.show_invitation,
       name='friends_show_invitation'),

    url(r'^invitation/(?P<invitation_id>[\d]+)/remove/$',
       views.remove_invitation,
       name='friends_remove_invitation'),

    url(r'^invitation/(?P<invitation_id>[\d]+)/accept/$',
       views.respond_to_invitation,
       {'resp': 'a'},
       name='friends_accept_invitation'),

    url(r'^invitation/(?P<invitation_id>[\d]+)/decline/$',
       views.respond_to_invitation,
       {'resp': 'd'},
       name='friends_decline_invitation'),

    url(r'^of_friend/(?P<username>[\.\w]+)/$',
        views.list_friend_friends,
        name='friends_friend_friends'),


]

friends/contrib/suggestions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from friends.utils import get_datetime_now
from friends.contrib.suggestions.managers import FriendshipSuggestionManager


class FriendshipSuggestion(models.Model):
    """
    A friendship suggestion connects two users that can possibly know each other.
    Suggestions can be created by somehow comparing some of user profiles fields
    (like city or address) or by importing user contacts from external services
    and then comparing names and email of imported contacts with users.
    """

    from_user = models.ForeignKey(User, verbose_name=_("from user"), related_name="suggestions_from")
    to_user = models.ForeignKey(User, verbose_name=_("to user"), related_name="suggestions_to")
    added = models.DateTimeField(_("added"), default=get_datetime_now)

    objects = FriendshipSuggestionManager()

    class Meta:
        unique_together = [("to_user", "from_user")]
        db_table = 'friends_suggestions_friendshipsuggestion'


class ImportedContact(models.Model):
    """
    Contact imported from external service.
    """
    # user who imported this contact
    owner = models.ForeignKey(User, verbose_name=_("owner"), related_name="imported_contacts")

    name = models.CharField(_("name"), max_length=100, null=True, blank=True)
    # Facebook does not give emails of user friends so email can be blank and
    # matching should be done using only name
    email = models.EmailField(_("email"), null=True, blank=True)

    added = models.DateTimeField(_("added"), default=get_datetime_now)

    @property
    def display_name(self):
        dname = ''
        if self.email:
            dname = self.email
        if dname and self.name:
            dname += " - "
        dname += self.name
        return dname

    def __unicode__(self):
		return _("%(display_name)s (%(owner)s's contact)") % {'display_name': self.display_name, 'owner': self.owner}

    class Meta:
        db_table = 'friends_suggestions_importedcontact'

sevalinks/forms.py
from django import forms
import configs

class UserRegisterForm(forms.Form):
    first_name = forms.CharField(label="First name",max_length=50, required=True)
    last_name = forms.CharField(label="Last name",max_length=50, required=True)
    username = forms.CharField(label="Username",max_length=50, required=True)
    email = forms.EmailField(label="Email", required=True)
    confirm_email = forms.EmailField(label="Confirm email", required=True)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput, required=True)
    confirm_password = forms.CharField(max_length=50, widget=forms.PasswordInput, required=True)
    phone_number = forms.IntegerField(label="Mobile number", required=True)
    cb = forms.CharField()
    
class UserLoginForm(forms.Form):    
    email = forms.EmailField(label="Email address", required=True)    
    password = forms.CharField(max_length=50, widget=forms.PasswordInput, required=True)
    
class ImageUploadForm(forms.Form):
    """Image upload form."""
    user_image = forms.ImageField()
    
class UserLocationForm(forms.Form):
    user_country = forms.CharField(max_length=50, required=True)
    user_state = forms.CharField(max_length=50, required=True, widget=forms.Select(choices=configs.STATES))
    user_area = forms.CharField(max_length=50, required=True)
    user_postcode = forms.CharField(max_length=10, required=True)
    
class UserStateForm(forms.Form):   
    user_state = forms.CharField(label="State", max_length=50, required=True, widget=forms.Select(choices=configs.STATES))
    
class UserProfessionForm(forms.Form):
    user_job_designation = forms.CharField(max_length=50, widget=forms.Select(choices=configs.DESIGNATION))
    user_experience = forms.CharField(max_length=50, required=True, widget=forms.Select(choices=configs.EXPERIENCE))
    user_industry = forms.CharField(max_length=50, widget=forms.Select(choices=configs.INDUSTRY))
    user_company = forms.CharField(max_length=50)
    user_profession = forms.CharField(max_length=50, required=True)
    user_description = forms.CharField()    
    

friends/contrib/suggestions/views.py
from urllib import urlencode

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required

from gdata.contacts.service import ContactsService

from friends.contrib.suggestions.backends.importers import GoogleImporter, FacebookImporter, TwitterImporter, YahooImporter, LinkedInImporter
from friends.contrib.suggestions.settings import RUNNER
from friends.contrib.suggestions.models import FriendshipSuggestion


@login_required
def suggested_friends(request, template_name="friends/suggestions/suggested_friends.html"):
    """
    List suggested friends.
    """
    suggested_friends = FriendshipSuggestion.objects.suggested_friends_for_user(request.user)
    return render_to_response(template_name,
                              {"suggested_friends": suggested_friends},
                              context_instance=RequestContext(request))


def _import_status(request, results):
    """
    Check import task state and set appropriate messages.
    Returns True if import is finished, False otherwise.
    """
    if results.ready():
        if results.status == "SUCCESS":
            messages.success(request, _("%(total)s contacts found, %(imported)s new contacts imported, %(suggestions)s new friendship suggestions added.") % results.result)
        elif results.status == "FAILURE":
            messages.error(request, message=_("There was an error importing your contacts."))
        return True
    else:
        messages.info(request, _("We're still importing your contacts. It shouldn't take too long."))
        request.session["import_contacts_task_id"] = results.task_id
        return False


@login_required
def import_contacts(request,
                    template_name="friends/suggestions/import_contacts.html",
                    extra_context=None):
    """
    If there is import_contacts_task_id in session pop it up and show info about
    this task using _import_status method.
    If there is no import_contacts_task_id in session check if there is 
    google_authsub_token, facebook_token, twitter_token, yahoo_token or
    linkedin_token in session and import contacts according to this token.
    """

    import_in_progress = False

    import_contacts_task_id = request.session.pop("import_contacts_task_id", None)
    if import_contacts_task_id:
        from celery.result import AsyncResult
        results = AsyncResult(import_contacts_task_id)
        import_in_progress = not _import_status(request, results)

    else:
        runner_class = RUNNER

        google_authsub_token = request.session.pop("google_authsub_token", None)
        if google_authsub_token:
            runner = runner_class(GoogleImporter,
                                  user=request.user,
                                  authsub_token=google_authsub_token)
            results = runner.import_contacts()
            import_in_progress = not _import_status(request, results)

        facebook_token = request.session.pop("facebook_token", None)
        if facebook_token:
            runner = runner_class(FacebookImporter,
                                  user=request.user,
                                  facebook_token=facebook_token)
            results = runner.import_contacts()
            import_in_progress = not _import_status(request, results)

        twitter_token = request.session.pop("twitter_token", None)
        if twitter_token:
            runner = runner_class(TwitterImporter,
                                  user=request.user,
                                  twitter_token=twitter_token)
            results = runner.import_contacts()
            import_in_progress = not _import_status(request, results)

        yahoo_token = request.session.pop("yahoo_token", None)
        if yahoo_token:
            runner = runner_class(YahooImporter,
                                  user=request.user,
                                  yahoo_token=yahoo_token)
            results = runner.import_contacts()
            import_in_progress = not _import_status(request, results)

        linkedin_token = request.session.pop("linkedin_token", None)
        if linkedin_token:
            runner = runner_class(LinkedInImporter,
                                  user=request.user,
                                  linkedin_token=linkedin_token)
            results = runner.import_contacts()
            import_in_progress = not _import_status(request, results)

    if not extra_context:
        extra_context = dict()
    extra_context['import_in_progress'] = import_in_progress
    return render_to_response(template_name,
                              extra_context,
                              context_instance=RequestContext(request))


def import_google_contacts(request, redirect_to=None):
    """
    If no token in GET params then redirect to Google page for granting permissions.
    If token is available, save it into session and redirect to import_contacts view. 
    """
    if redirect_to is None:
        redirect_to = reverse("friends_suggestions_import_contacts")
    if "token" in request.GET:
        request.session["google_authsub_token"] = request.GET["token"]
        return HttpResponseRedirect(redirect_to)
    authsub_url = ContactsService().GenerateAuthSubURL(next=request.build_absolute_uri(),
                                                       scope='http://www.google.com/m8/feeds/',
                                                       secure=False,
                                                       session=True)
    return HttpResponseRedirect(authsub_url)


@login_required
def import_facebook_contacts(request, access=None, auth_token=None):
    """
    If no auth_token is available redirect to Facebook page.
    If auth_token is availabe, save it into session and redirect to import_contacts view.
    """
    if auth_token:
        request.session["facebook_token"] = auth_token
        return HttpResponseRedirect(reverse("friends_suggestions_import_contacts"))
    else:
        return HttpResponseRedirect("%s?%s" % (
            reverse("oauth_access_login", args=["facebook", ]),
            urlencode({
                "next": request.build_absolute_uri()
            })
        ))


@login_required
def import_twitter_contacts(request, access=None, auth_token=None):
    """
    """
    if auth_token:
        request.session["twitter_token"] = auth_token
        return HttpResponseRedirect(reverse("friends_suggestions_import_contacts"))
    else:
        return HttpResponseRedirect("%s?%s" % (
            reverse("oauth_access_login", args=["twitter", ]),
            urlencode({
                "next": request.build_absolute_uri()
            })
        ))


@login_required
def import_yahoo_contacts(request, access=None, auth_token=None):
    """
    """
    if auth_token:
        request.session["yahoo_token"] = auth_token
        return HttpResponseRedirect(reverse("friends_suggestions_import_contacts"))
    else:
        return HttpResponseRedirect("%s?%s" % (
            reverse("oauth_access_login", args=["yahoo", ]),
            urlencode({
                "next": request.build_absolute_uri()
            })
        ))


@login_required
def import_linkedin_contacts(request, access=None, auth_token=None):
    """
    """
    if auth_token:
        request.session["linkedin_token"] = auth_token
        return HttpResponseRedirect(reverse("friends_suggestions_import_contacts"))
    else:
        return HttpResponseRedirect("%s?%s" % (
            reverse("oauth_access_login", args=["linkedin", ]),
            urlencode({
                "next": request.build_absolute_uri()
            })
        ))

friends/templates/friends/base.html
{% extends "sevalinks/base.html" %}

{% block title %}Sevalinks - {% block friends_title %}{% endblock %}{% endblock %}

{% block top_menu %}
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">SevaLinks</a>
      <ul class="right hide-on-med-and-down">      	
        <li class="active"><a href="/seva/myaccount/">My Account</a></li>
        <li><a href="/seva/add/">Add</a></li>
        <li><a href="/seva/logout/">Logout</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
      	<li class="active"><a href="/seva/myaccount/">My Account</a></li>
        <li><a href="/seva/add/">Add</a></li>
        <li><a href="/seva/logout/">Logout</a></li>        
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav> 
{% endblock %}

{% block main_content %}
<div class="section no-pad-bot" id="index-banner">
<div class="container">
<div class="row">	
      <div class="col s12 m4 l3  grey lighten-4">
        <!-- Grey navigation panel -->
        <br />
        <div class="center">
	    	<div class="card">
		    <div class="card-image waves-effect waves-block waves-light">
		      <img class="activator" style="width:200px;height:200px;" src="{% if user_image %}{{ user_image}}{% else %}/static/userimages/default_user.png{% endif %}">
		    </div>
		    <div class="card-content">
		      <p class="center"><a href="#user_image_modal">Change</a></p>
		    </div>		    
		  </div>
		</div>        
        <!--div class="center" ><img style="height: 200px;width: 200px;" src="/static/userimages/default_user.png"></div-->       
        <p class="center" ><a href="/seva/myaccount/">Profile</a></p>
		<p class="center" ><a href="/friends/">My Network</a></p>		
		<p class="center" ><a href="/seva/upgrade/">Upgrade</a></p>
        <p class="center" ><a href="/seva/changepassword/">Change Password</a></p>        
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
      </div>     

{% block friends_content %}{% endblock %}
      
</div>
</div>
</div>

<div id="user_image_modal" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h5 class="header center orange-text" >Your Image seen by others</h5>
      <form action="/seva/addimage/" method="post" enctype="multipart/form-data">
  		{% csrf_token %}
      <div class="row">      		     	
	    	<div class="col s12">
	    	<div class="col s4">
		    	<div class="card">
			    <div class="card-image waves-effect waves-block waves-light">
			      <img class="activator" style="width:200px;height:200px;" src="{% if user_image %}{{ user_image}}{% else %}/static/userimages/default_user.png{% endif %}">
			    </div>			    		    
			  </div>
		  	</div>
		  	</div>
		  	<div class="col s12">
		    <div class="input-field col s6">		    		    	
			    <input id="id_user_image" type="file" class="" name="user_image">
	  		</div>
  			</div>
		  	<div class="col s12">
		    <div class="input-field col s6">		    		    	
			    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
		    	<i class="material-icons right">send</i>
		  		</button>
	  		</div>
  			</div>
  			
	  </div>	  
	  </form>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>
{% endblock %}
{% block js_content %}
<script type="text/javascript">
$(document).ready(function(){   
    $('.modal').modal();
  });
  </script>
{% endblock %}

friends/templates/friends/blocked_users_list.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}{% trans "Blocked users" %}{% endblock %}

{% block friends_content %}
<ul>
{% for friend in friends %}
	<li><a href="{% url 'profile_detail' username=friend.username %}">{{ friend }}</a> (<a href="{% url 'friends_unblock_user' friend.username %}">{% trans "unblock" %}</a>)</li>
{% endfor %}
</ul>
{% endblock %}

friends/templates/friends/friend_invite.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}{% blocktrans %}Invite {{ friend }} to your friends{% endblocktrans %}{% endblock %}

{% block friends_content %}
<form action="" method="post">{% csrf_token %}
	<fieldset>
		{{ form.as_p }}
	</fieldset>
	<input type="submit" value="{% trans "Invite" %}" />
</form>
{% endblock %}

friends/templates/friends/friend_remove.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}{% blocktrans %}Remove {{ friend }} from your friends{% endblocktrans %}{% endblock %}

{% block friends_content %}
<form action="" method="post">{% csrf_token %}
	<p>{% blocktrans %}Are you sure you want to remove {{ friend }} from your friends?{% endblocktrans %}</p>
	<fieldset>
		{{ form.as_p }}
	</fieldset>
	<input type="submit" value="{% trans "Remove" %}" />
</form>
{% endblock %}

friends/templates/friends/friends_list.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}{% trans "Friends" %}{% endblock %}

{% block friends_content %}
<ul>
{% for friend in friends %}
	<li><a href="{% url 'profile_detail' username=friend.username %}">{{ friend }}</a> (<a href="{% url 'friends_remove' friend.username %}">{% trans "remove from friends" %}</a>)</li>
{% endfor %}
</ul>
{% endblock %}

friends/templates/friends/friends_of_friend.html
{% extends 'friends/base.html' %}
{% load i18n friends_tags %}

{% block friends_title %}{% blocktrans %}{{ friend }}'s friends{% endblocktrans %}

{% block friends_content %}
<ul>
{% for friend in friends %}
	{% are_friends user friend as are_friends %}
	<li><a href="{% url 'profile_detail' username=friend.username %}">{{ friend }}</a> ({% if are_friends %}<a href="{% url 'friends_remove' friend.username %}">{% trans "remove from friends" %}</a>{% else %}<a href="{% url 'friends_invite' friend.username %}">{% trans "invite to friends" %}</a>{% endif %})</li>
{% endfor %}
</ul>
{% endblock %}

friends/templates/friends/invitation_show.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}
{% if user == invitation.to_user %}{% blocktrans with invitation.from_user as from_user %}Friends request from {{ from_user }}{% endblocktrans %}{% endif %}
{% if user == invitation.from_user %}{% blocktrans with invitation.to_user as to_user %}Friends request to {{ to_user }}{% endblocktrans %}{% endif %}
{% endblock %}

{% block friends_content %}
<div>
	{{ invitation.message }}

	<p class="buttons">
		{% if user == invitation.to_user %}
			<a href="{% url 'friends_accept_invitation' invitation.pk %}">{% trans "Accept" %}</a>
			<a href="{% url 'friends_decline_invitation' invitation.pk %}">{% trans "Decline" %}</a>
			<a href="{% url 'friends_block_user' invitation.from_user.username %}">{% trans "Decline and block" %}</a>
		{% endif %}
		{% if user == invitation.from_user %}
			<a href="{% url 'friends_remove_invitation' invitation.pk %}">{% trans "Delete" %}</a>
		{% endif %}
	</p>
</div>
{% endblock %}

friends/templates/friends/invitations_list.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}{% if status == 'received' %}{% trans "Received invitations" %}{% endif %}{% if status == 'sent' %}{% trans "Sent invitations" %}{% endif %}{% endblock %}

{% block friends_content %}
<table>
	<thead>
		<tr>
			<th>{% if status == 'received' %}{% trans "From" %}{% endif %}{% if status == 'sent' %}{% trans "To" %}{% endif %}</th>
			<th>{% if status == 'received' %}{% trans "Received" %}{% endif %}{% if status == 'sent' %}{% trans "Sent" %}{% endif %}</th>
			<th>{% trans "Invitation" %}</th>
		</tr>
	</thead>
	<tbody>{% for invitation in invitations %}
		<tr>
			<td>
				<a href="{% if status == 'received' %}{% url 'profile_detail' username=from_user.username %}{% endif %}{% if status == 'sent' %}{% url 'profile_detail' username=to_user.username %}{% endif %}">{% if status == 'received' %}{{ invitation.from_user }}{% endif %}{% if status == 'sent' %}{{ invitation.to_user }}{% endif %}</a>
			</td>
			<td>{{ invitation.sent }}</td>
			<td>
				<a href="{% url 'friends_show_invitation' invitation.pk %}">{% trans "Details" %}</a>
			</td>
		</tr>{% endfor %}
	</tbody>
</table>
{% endblock %}

friends/templates/friends/user_block.html
{% extends 'friends/base.html' %}
{% load i18n %}

{% block friends_title %}{% blocktrans %}Block {{ blocked }} from sending invitations{% endblocktrans %}{% endblock %}

{% block friends_content %}
<form action="" method="post">{% csrf_token %}
	<p>{% blocktrans %}Are you sure you want to block {{ blocked }} from sending you invitations?{% endblocktrans %}</p>
	<fieldset>
		{{ form.as_p }}
	</fieldset>
	<input type="submit" value="{% trans "Block" %}" />
</form>
{% endblock %}